### ISSUE TITLE
API 是否应该命名为 GoLocal 或者 RoutineLocal 而非 ThreadLocal ？

### ISSUE THREAD

**Issue by JasonMing** [timandy/routine#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Go 里面并没有直接管控 “Thread” 的能力，都是 GoRoutine，所以，这个 “Local” 其实是对 GoRoutine 的。
虽然 “ThreadLocal” 能很好对接从 Java 过来的开发人员，但实际上这个命名并不是很妥当。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timandy** [comment]
@JasonMing Thanks for your suggestions. Please use English for other personnel to review.

 > Go 里面并没有直接管控 “Thread” 的能力，都是 GoRoutine，所以，这个 “Local” 其实是对 GoRoutine 的。
虽然 “ThreadLocal” 能很好对接从 Java 过来的开发人员，但实际上这个命名并不是很妥当。

You can think of the `Thread` as a virtual thread, a coroutine in go. Because the API name has already been determined, there are no plans to rename the API at this time. Subsequent releases may consider this change.
